version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  dev:
    build: .
    container_name: xray_app
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - rabbitmq
    env_file:
     - .env
    command: pnpm run start:dev

  prod:
    build: .
    container_name: xray_app
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - rabbitmq
    env_file:
     - .env
    command: pnpm run start:prod

volumes:
  mongo_data:
